import "dotenv/config";
import mongoose from "mongoose";
import MenuItem from "../models/MenuItem.js";
import connectDB from "../config/db.js";

const dishes = [
  // ── DRINKS ──
  { name: "Black Coffee", slug: "black-coffee", description: "Completely roasted and boiled in hot water.", priceKES: 80, category: "drinks", image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80", popular: true, vegan: true, spicy: false },
  { name: "Fresh Juice", slug: "fresh-juice", description: "Fine fresh blend of mango served either cold or warm.", priceKES: 120, category: "drinks", image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=800&q=80", popular: true, vegan: true, spicy: false },
  { name: "Afia", slug: "afia", description: "Different flavours served warm or ice chilled.", priceKES: 120, category: "drinks", image: "https://images.unsplash.com/photo-1473347303946-62fb4c5a5e5f?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },
  { name: "Black Chocolate", slug: "black-chocolate", description: "Melted dark chocolate dipped in warm milk.", priceKES: 80, category: "drinks", image: "https://images.unsplash.com/photo-1517578239113-b03992dcdd25?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },
  { name: "Soda", slug: "soda", description: "Served either warm or ice chilled.", priceKES: 130, category: "drinks", image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80", popular: true, vegan: true, spicy: false },
  { name: "Milk And Tea", slug: "milk-and-tea", description: "Served with chapati or mandazi.", priceKES: 80, category: "drinks", image: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=800&q=80", popular: true, vegan: true, spicy: false },
  { name: "Minute Maid", slug: "minute-maid", description: "Different flavours served warm or ice chilled.", priceKES: 120, category: "drinks", image: "https://images.unsplash.com/photo-1603569283847-aa295f0d016a?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },
  { name: "White Chocolate", slug: "white-chocolate", description: "Served hot with mandazi or chapati.", priceKES: 80, category: "drinks", image: "https://images.unsplash.com/photo-1542990253-a781e04e0571?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },
  { name: "Mala", slug: "mala", description: "Served ice chilled cold in a bowl with ugali.", priceKES: 100, category: "drinks", image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },
  { name: "White Coffee", slug: "white-coffee", description: "Partially roasted coffee beans boiled or sifted in boiled water.", priceKES: 120, category: "drinks", image: "https://images.unsplash.com/photo-1485808191679-5f86510bd9d4?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },

  // ── SPECIAL DISHES ──
  { name: "Meatballs With Ugali, Spaghetti Or Rice", slug: "meatballs", description: "Perfectly barbecued meatballs perfectly spiced and served with ugali, rice or spaghetti.", priceKES: 400, category: "mains", image: "https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=800&q=80", popular: true, vegan: false, spicy: false },
  { name: "Full Wet/Dry Fry Kienyeji Chicken", slug: "full-kienyeji-chicken", description: "Served with sauce and kachumbari.", priceKES: 1500, category: "mains", image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=800&q=80", popular: true, vegan: false, spicy: false },
  { name: "Chicken Burrito", slug: "chicken-burrito", description: "Thin chicken cuts fried and wrapped.", priceKES: 400, category: "mains", image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80", popular: true, vegan: false, spicy: false },
  { name: "Chicken Biryani", slug: "chicken-biryani", description: "Chicken cuts fried and tossed in spiced basmati rice.", priceKES: 500, category: "mains", image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", popular: true, vegan: false, spicy: true },
  { name: "Fish Fingers And Chips", slug: "fish-fingers-chips", description: "Served with dipping sauce.", priceKES: 450, category: "mains", image: "https://images.unsplash.com/photo-1544982503-9f984c14501a?auto=format&fit=crop&w=800&q=80", popular: false, vegan: false, spicy: false },
  { name: "Fish Fillet And Chips", slug: "fish-fillet-chips", description: "Served with sauce and kachumbari.", priceKES: 400, category: "mains", image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80", popular: false, vegan: false, spicy: false },
  { name: "Chips Mixed In Beef", slug: "chips-mixed-beef", description: "Rib eye steak, frozen french fries, tomato sauce, fresh vegetable salads.", priceKES: 450, category: "mains", image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80", popular: true, vegan: false, spicy: false },
  { name: "Ossubucco", slug: "ossubucco", description: "Cow leg pepper soup lightly salted.", priceKES: 300, category: "mains", image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80", popular: false, vegan: false, spicy: true },
  { name: "Full Chicken Bahati", slug: "full-chicken-bahati", description: "Grilled till tender and served with kachumbari.", priceKES: 1600, category: "mains", image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=800&q=80", popular: true, vegan: false, spicy: false },

  // ── DISHES ──
  { name: "Ndengu", slug: "ndengu", description: "Dried mung beans, coconut milk, curry powder, garam.", priceKES: 130, category: "mains", image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },
  { name: "Ugali", slug: "ugali", description: "Stiff maize porridge.", priceKES: 100, category: "sides", image: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80", popular: true, vegan: true, spicy: false },
  { name: "Chips Zege", slug: "chips-zege", description: "French fried cooked in eggs and served with kachumbari or sauce.", priceKES: 220, category: "sides", image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80", popular: true, vegan: false, spicy: false },
  { name: "Beans", slug: "beans", description: "Allowed to simmer in coconut milk.", priceKES: 130, category: "mains", image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },
  { name: "Mukimo", slug: "mukimo", description: "Smothered mataha served with kachumbari.", priceKES: 150, category: "mains", image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },
  { name: "Matoke", slug: "matoke", description: "Green bananas tossed in potato and other veggies.", priceKES: 150, category: "vegan", image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },
  { name: "Grilled Chicken", slug: "grilled-chicken", description: "Quarter sized broiler chicken, grilled.", priceKES: 250, category: "mains", image: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80", popular: true, vegan: false, spicy: false },
  { name: "Beef", slug: "beef", description: "Red wine, balsamic vinegar, boneless beef chuck.", priceKES: 300, category: "mains", image: "https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=800&q=80", popular: false, vegan: false, spicy: false },
  { name: "Fish", slug: "fish", description: "Wet or dry fried fish.", priceKES: 350, category: "mains", image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80", popular: false, vegan: false, spicy: false },
  { name: "Kienyeji Chicken", slug: "kienyeji-chicken", description: "Free range chicken cuts, stewed, boiled or deep fried.", priceKES: 350, category: "mains", image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=800&q=80", popular: true, vegan: false, spicy: false },
  { name: "Greens", slug: "greens", description: "Green leafy veggies steamed.", priceKES: 70, category: "vegan", image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },
  { name: "Matumbo", slug: "matumbo", description: "Wet fried matumbo.", priceKES: 230, category: "mains", image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80", popular: false, vegan: false, spicy: false },
  { name: "Minji", slug: "minji", description: "Allowed to simmer in coconut milk.", priceKES: 180, category: "mains", image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },
  { name: "Cabbage", slug: "cabbage", description: "Steamed white cabbage.", priceKES: 70, category: "vegan", image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },
  { name: "Chapati", slug: "chapati", description: "Unleavened disk-shaped flat bread made of wheat flour with a stew.", priceKES: 50, category: "sides", image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80", popular: true, vegan: true, spicy: false },
  { name: "White Rice", slug: "white-rice", description: "Boiled white rice.", priceKES: 150, category: "sides", image: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },
  { name: "Pilau", slug: "pilau", description: "Rice cooked in broth, mixed spices and other ingredients.", priceKES: 200, category: "mains", image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80", popular: true, vegan: false, spicy: true },
  { name: "Githeri", slug: "githeri", description: "Lightly spiced and served with veggie salad dressing.", priceKES: 160, category: "mains", image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },

  // ── SNACKS ──
  { name: "Chips", slug: "chips", description: "Deep fried till crisp and golden brown and served with kachumbari.", priceKES: 200, category: "sides", image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80", popular: true, vegan: true, spicy: false },
  { name: "Andazi", slug: "andazi", description: "Even stuffing of dough deep fried till golden brown.", priceKES: 40, category: "sides", image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80", popular: false, vegan: true, spicy: false },
  { name: "2 Samosas", slug: "samosas", description: "Pastry stuffed with minced meat filling then deep fried and served with kachumbari.", priceKES: 150, category: "sides", image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80", popular: true, vegan: false, spicy: false },
  { name: "Kebab", slug: "kebab", description: "Served on a skewer accompanied with kachumbari.", priceKES: 130, category: "sides", image: "https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=800&q=80", popular: false, vegan: false, spicy: false },
  { name: "2 Sausages", slug: "sausages", description: "Served with kachumbari and sauce.", priceKES: 150, category: "sides", image: "https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=800&q=80", popular: false, vegan: false, spicy: false },
];

await connectDB();
await MenuItem.deleteMany({});
await MenuItem.insertMany(dishes);
console.log(`Seeded ${dishes.length} menu items`);
await mongoose.disconnect();
process.exit(0);